name: build

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mypy
        pip install yapf
    - name: Check types with mypy
      # Get all files with find because ** doesn't expand correctly.
      run: |
        find . -iname '*.py' | xargs mypy
    - name: Check formatting with yapf
      run: |
        yapf --diff --recursive .
    - name: Test with unittest
      run: |
        python -m unittest
